package com.ky_proj.spjplugin.util

/**
 * Created on 2018/01/19.
 */
class GetSpjCommands private constructor() {

    val list: Array<String>
        get() =
            arrayOf(
                    "Add()",
                    "Append()",
                    "AppendArray()",
                    "CGICall()", "CheckCount()",
                    "CheckDatabase()",
                    "CHeckDate()",
                    "CheckInput()",
                    "CheckItem()",
                    "CheckKana()",
                    "CheckSize()",
                    "CheckTime()",
                    "CompareNumeric()",
                    "ConvertString()",
                    "ConvertUnicodeString()",
                    "ConvertUnicodeStringArray()",
                    "CountArray()",
                    "Date()",
                    "DateTime()",
                    "DayOfTheWeek()",
                    "Divide()",
                    "Equals()",
                    "EqualsIgnoreCase()",
                    "ExecutePreparedSQL()",
                    "ExecuteSQL()",
                    "ExistFile()",
                    "ExistFormVariable()",
                    "ExistSessionVariable()",
                    "ExtractNumeric()",
                    "FormatComma()",
                    "FTPDownload()",
                    "FTPUpload()",
                    "GetCookie()",
                    "GetElement()",
                    "GetElementIndex()",
                    "GetResourceString()",
                    "HttpHeader()",
                    "HttpRequestEnv()",
                    "InsertElement()",
                    "JoinString()",
                    "Length()",
                    "LengthFormVariable()",
                    "Lower()",
                    "MakeArray()",
                    "MakeDir()",
                    "MakePassword()",
                    "MakeSequence()",
                    "MIMEDecode()",
                    "MIMEEncode()",
                    "Mod()",
                    "Multiply()",
                    "QuerySQL()",
                    "ReadImageFile()",
                    "RemoveElement()",
                    "RemoveFile()",
                    "RenameFile()",
                    "ReplaceCharacter()",
                    "ReplaceCharCode()",
                    "ReplaceMarker()",
                    "RomajiToKana()",
                    "SelectMultipleList()",
                    "SendError()",
                    "SendRedirect()",
                    "SeparateString()",
                    "SetCookie()",
                    "SetElement()",
                    "SetError()",
                    "SetFormValue()",
                    "SetHttpHeader()",
                    "SetValueArray()",
                    "SQLFunctionCall()",
                    "SQLProcedureCall()",
                    "SQLProcedureResultSet()",
                    "SQLResultArray()",
                    "SQLResultColumnCount()",
                    "SQLResultCount()",
                    "SQLResultElement()",
                    "SQLResultRow()",
                    "SQLResultRowArray()",
                    "SQLResultUnion()",
                    "Substring()",
                    "Subtract()",
                    "SwitchCase()",
                    "TagOption()",
                    "Time()",
                    "TrimLeft()",
                    "TrimRight()",
                    "UnionArray()",
                    "Upload()",
                    "Upper()",
                    "Wait()"
            )
    companion object {
        internal val instance = GetSpjCommands()
    }
}
